[build]
  command = "node scripts/changelog/generate-changelog.js"
  publish = "."

[[redirects]]
  from = "/"
  to = "/auth"
  status = 302

[[redirects]]
  from = "/auth"
  to = "/auth.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/index.html"
  status = 200
